sourcio/crowd_sourcing/urls.py
from django.urls import path

from . import views

app_name = 'crowd_sourcing'
urlpatterns = [
    path('', views.index, name="index"),
    path('chaine/', views.chaine, name="chaine"),
    path('chaine/<int:chaine_id>', views.chaine, name="chaine"),
    path('collectif/', views.collectif, name="collectif"),
    path('collectif/<int:collectif_id>', views.collectif, name="collectif"),
    path('source/<int:source_id>', views.source, name="source"),
    path('source/', views.source, name="source"),
    path('video/<int:video_id>', views.video, name="video"),
]

sourcio/sourcio/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [

    path('admin/', admin.site.urls),
    path('', include('crowd_sourcing.urls')),

]

sourcio/crowd_sourcing/models.py
from django.db import models

#############
# COLLECTIF #
#############
class Collectif(models.Model):
    nom = models.CharField(max_length = 30)
    url = models.URLField(null = True, blank = True)
    date_creation = models.TimeField(null = True, blank = True)

    def __repr__(self):
        return "{nomClasse}({id!s}) - {nom}".format(nomClasse = __class__.__name__, id = self.id, nom = self.nom)
    def __str__(self):
        return self.nom

##########
# CHAINE #
##########
class ChaineSexe(models.Model):
    valeur = models.IntegerField(null = True, blank = True)
    description = models.CharField(max_length = 50, null = True, blank = True)

class ChaineDomaine(models.Model):
    valeur = models.IntegerField(null = True, blank = True)
    description = models.CharField(max_length = 50, null = True, blank = True)

class Chaine(models.Model):
    nom = models.CharField(max_length = 64)
    url = models.CharField(max_length = 64, default = "", blank = True)
    date_creation = models.DateField(null = True, blank = True)
    collectif = models.ForeignKey(Collectif, on_delete = models.SET_NULL, null = True, blank = True)
    sexe_presentateur = models.ForeignKey(ChaineSexe, on_delete = models.SET_NULL, null = True, blank = True)
    domaine = models.ForeignKey(ChaineDomaine, on_delete = models.SET_NULL, null = True, blank = True)
    observation = models.TextField(default = "", blank = True)
    mise_a_jour = models.DateField(auto_now = True, null = True, blank = True)

    #abonnements = models.IntegerField(null = True, blank = True)

    def __repr__(self):
        return "{nomClasse}({id!s}) - {nom}".format(nomClasse = __class__.__name__, id = self.id, nom = self.nom)

    def __str__(self):
        return self.nom

class ChaineAbonnement(models.Model):
    chaine = models.ForeignKey(Chaine, on_delete = models.CASCADE)
    date = models.DateField(null = True, blank = True)
    nombre = models.IntegerField(null = True, blank = True)

#########
# VIDEO #
#########
class Video(models.Model):
    yt_id = models.CharField(max_length = 11) # Also URL
    date_publication = models.DateField(null = True, blank = True)
    titre = models.CharField(max_length = 90, default = "", blank = True)
    chaine = models.ForeignKey(Chaine, on_delete = models.PROTECT, null = True, blank = True)
    vulgarisation = models.BooleanField(default = True)
    sourcee = models.BooleanField(default = False)
    vues = models.BigIntegerField(null = True, blank = True)
    duree = models.TimeField(null = True, blank = True)
    description = models.TextField(default = "", blank = True)

    mise_a_jour = models.DateField(auto_now = True, null = True, blank = True)
    # Commentaires ?

    def __repr__(self):
        return "{nomClasse}({id!s}) - {nom}".format(nomClasse = __class__.__name__, id = self.id, nom = self.titre)

    def __str__(self):
        return "{chaine}: {titre}".format(chaine = self.chaine, titre = self.titre)

##########
# SOURCE #
##########
class Source(models.Model):
    nom = models.CharField(max_length = 100)
    timestamp_creation = models.DateTimeField(auto_now_add = True)
    video = models.ForeignKey(Video, on_delete = models.PROTECT, null = True, blank = True)
    seulement_citee = models.BooleanField(null = True, blank = True)
    source_personnelle = models.BooleanField(null = True, blank = True)
    time_code = models.TimeField(null = True, blank = True)
    description = models.TextField(default = "", blank = True)

    type_source = models.CharField(max_length = 50, default = "", blank = True)
    auteur_source = models.CharField(max_length = 50, default = "", blank = True)
    data_publication = models.DateField(null = True, blank = True)
    lieu = models.CharField(max_length = 50, default = "", blank = True)
    espace_inscription_disciplinaire = models.CharField(max_length = 50, default = "", blank = True)
    lieu_acces_publication = models.CharField(max_length = 50, default = "", blank = True)
    lieu_implantation_publication = models.CharField(max_length = 50, default = "", blank = True)

    mise_a_jour = models.DateField(auto_now = True, null = True, blank = True)

    def __repr__(self):
        return "{nomClasse}({id!s}) - {nom}".format(nomClasse = __class__.__name__, id = self.id, nom = self.nom)

    def __str__(self):
        return "{video} - [{nom}]".format(video = self.video, nom = self.nom)

class SourceURL(models.Model):
    source = models.ForeignKey(Source, on_delete = models.PROTECT)
    url = models.URLField(null = True, blank = True)
    info = models.TextField(null = True, blank = True)

    def __repr__(self):
        return "{nomClasse}({id!s}) - {nom}".format(nomClasse = __class__.__name__, id = self.id, nom = self.url)

    def __str__(self):
        return "{source} ({url})".format(source = self.source, url = self.url)

sourcio/crowd_sourcing/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse
from django.db.models import Sum

from .models import Chaine, ChaineAbonnement, Collectif, Source, SourceURL, Video

# Create your views here.
def index(request):
    video_list = Video.objects.filter(vulgarisation = True).order_by('-date_publication')[:6]
    source_list = Source.objects.order_by('-timestamp_creation')[:6]

    actuel = Video.objects.filter(vulgarisation = True).filter(sourcee = True).count()
    total_vulgarisation = Video.objects.filter(vulgarisation = True).count()
    total = Video.objects.count()
    progression = {
        'actuel': actuel,
        'total_vulgarisation': total_vulgarisation,
        'total': total,
        'pourcentage' : actuel / total_vulgarisation * 100,
        }
    context = {'video_list': video_list, 'source_list': source_list, 'progression': progression}

    return render(request, 'crowd_sourcing/index.html', context)

# Lister les chaines ou voir les détails d'une
def chaine(request, chaine_id = None):
    if chaine_id == None:
        return render(request, 'crowd_sourcing/chaines.html', {'chaine': Chaine.objects.all().order_by('nom')})

    chaine = get_object_or_404(Chaine, pk=chaine_id)
    stats = {
        "vues": Video.objects.filter(chaine=chaine_id).filter(vulgarisation = True).aggregate(Sum('vues')).get("vues__sum"),
        "vues_total": Video.objects.filter(chaine=chaine_id).aggregate(Sum('vues')).get("vues__sum"),
        "vulgarisation": Video.objects.filter(chaine=chaine_id).filter(vulgarisation = True).count(),
        "sourcees": Video.objects.filter(chaine=chaine_id).filter(sourcee = True).count(),
        "total": Video.objects.filter(chaine=chaine_id).count(),
    }
    abonnement = ChaineAbonnement.objects.filter(chaine = chaine_id)
    print(abonnement)
    video = Video.objects.filter(chaine=chaine_id)
    return render(request, 'crowd_sourcing/chaine.html', {'chaine': chaine, 'abonnement': abonnement, 'video': video, 'stats': stats} )

# Lister les collectif ou voir les détails d'un
def collectif(request, collectif_id = None):
    if collectif_id == None:
        return render(request, 'crowd_sourcing/collectifs.html', {'collectif': Collectif.objects.all()})

    collectif = get_object_or_404(Collectif, pk=collectif_id)
    chaine = Chaine.objects.filter(collectif=collectif.id)
    return render(request, 'crowd_sourcing/collectif.html', {'collectif': collectif, 'chaine': chaine})

# Ajouter ou lister les sources
def source(request, source_id = None):
    source = get_object_or_404(Source, pk=source_id)
    url = SourceURL.objects.filter(source=source_id)
    return render(request, 'crowd_sourcing/source.html', {'source': source, 'url': url})

# Lister les vidéos et détail d'une vidéo
def video(request, video_id):
    video = get_object_or_404(Video, pk=video_id)
    sources = Source.objects.filter(video = video)
    return render(request, 'crowd_sourcing/video.html', {'video': video, 'source': sources})

sourcio/crowd_sourcing/templates/crowd_sourcing/chaine.html
<h1>{{ chaine.nom }}</h1>

{% if chaine.collectif != None %}
  <h3><a href="{% url 'crowd_sourcing:collectif' chaine.collectif.id %}">{{ chaine.collectif }}</h3>
{% endif %}
{% if chaine.url != None %}
  <p><a href="https://youtube.com/{{chaine.url}}">Voir sur youtube</a></p>
{% endif %}
<p>Créée le: {{ chaine.date_creation }} </p>

<p>Sexe du présentateur: {{chaine.sexe_presentateur.description }}</p>
<p>Domaine: {{chaine.domaine.description }}</p>

{# if #}
<p>Abonnements</p>
<ul>
{% for enregistrement in abonnement %}
  <li>{{ enregistrement.date }} - {{ enregistrement.nombre }}</li>
{% endfor %}

</ul>
{% if stats.vues != None %}
  <p>{{ stats.vues }} vues de vidéos de vulgarisation ({{ stats.vues_total }} au total)</p>
{% endif %}

<p>MàJ: {{ chaine.mise_a_jour }}</p>

{% if chaine.observation != "" %}
  <p>Observations:</p>
  <textarea>
    {{ chaine.observation }}
  </textarea>
{% endif %}

<h3>Vidéos</h3>
<!-- Stats -->
<p>Vidéos de vulgarisation: {{ stats.vulgarisation }} / {{ stats.total }}</p>
<!-- Progression -->
<p>Vidéos sourcées: {{ stats.sourcees }} / {{ stats.total }}</p>
<!-- Liste -->
<ul>
{% for enregistrement in video %}
  <li>
    <a href="{% url 'crowd_sourcing:video' enregistrement.id %}">
      <img src="https://i.ytimg.com/vi/{{enregistrement.yt_id}}/hqdefault.jpg" style="width:128px" />
      {{ enregistrement.titre }}
    </a>
  </li>
{% endfor %}
</ul>

sourcio/crowd_sourcing/templates/crowd_sourcing/chaines.html
<ul>
{% for enregistrement in chaine %}
  <li><a href="{% url 'crowd_sourcing:chaine' enregistrement.id %}">{{ enregistrement.nom }}</a></li>
{% endfor %}
</ul>

sourcio/crowd_sourcing/templates/crowd_sourcing/collectif.html
<h1><a href="{{ collectif.url }}">{{ collectif.nom }}</a></h1>

<p>Date de création: {{ collectif.date_creation}}</p>

<ul>
{% for enregistrement in chaine %}
  <li><a href="{% url 'crowd_sourcing:chaine' enregistrement.id %}"> {{ enregistrement.nom }} </a></li>
{% endfor %}
</ul>

sourcio/crowd_sourcing/templates/crowd_sourcing/collectifs.html
<ul>
{% for enregistrement in collectif %}
  <li><a href="{% url 'crowd_sourcing:collectif' enregistrement.id %}">{{ enregistrement.nom }}</a></li>
{% endfor %}
</ul>

sourcio/crowd_sourcing/templates/crowd_sourcing/index.html
<a href="{% url 'crowd_sourcing:collectif' %}">Collectifs</a>
<a href="{% url 'crowd_sourcing:chaine' %}">Chaines</a>

<h1>Progression ({{ progression.pourcentage }} %)</h1>
<p>{{ progression.actuel }} / {{ progression.total_vulgarisation }} ({{ progression.total }})</p>

<h1>Vidéos récentes</h1>
<ul>
{% for video in video_list %}
  <li><a href="{% url 'crowd_sourcing:video' video.id %}">{{ video.titre }}</a></li>
{% endfor %}
</ul>

<h1>Sources récentes</h1>
<ul>
{% for source in source_list %}
  <li><a href="{% url 'crowd_sourcing:source' source.id %}">{{ source.nom }}</a></li>
{% endfor %}
</ul>

sourcio/crowd_sourcing/templates/crowd_sourcing/source.html
<h1>{{ source.nom }}</h1>

<p>Création: {{ source.timestamp_creation }}</p>
<p>Vidéo: <a href="{% url 'crowd_sourcing:video' source.video.id %}">{{ source.video }}</a></p>
<p>Citée mais non référencée: {{source.seulement_citee}}</p>
<p>Source personnelle (autocitation): {{source.source_personnelle}}</p>
<!-- TODO: Fix Time_code -->
<p>Time code: <a href="https://youtube.com/watch?v={{ source.video.yt_id }}&t={{ source.time_code }}">{{ source.time_code }}</a></p>
<p>Description:<br>
{{ source.description | linebreaks }}</p>

<h3>URL</h3>
<ul>
{% for enregistrement in url %}
  <li>
    <a href="{{ enregistrement.url }}">
      {{ enregistrement.url }}<br>
      {{ enregistrement.info }}
    </a>
  </li>
{% endfor %}
</ul>

sourcio/crowd_sourcing/templates/crowd_sourcing/video.html
<h1>{{video.titre}}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<iframe width="560" height="315" src="https://www.youtube.com/embed/{{video.yt_id}}" frameborder="0" allow="encrypted-media; picture-in-picture" allowfullscreen></iframe>

<h3><a href="{% url 'crowd_sourcing:chaine' video.chaine.id %}">{{video.chaine}}</a></h3>

<p>Publiée le {{video.date_publication}}</p>
<p>{{video.vues}} vues</p>
<p>Vidéo de vulgarisation: {{video.vulgarisation}}</p>
<p>Sourcée: {{video.sourcee}}</p>
<p>Description:<br>
  {{video.description | linebreaks | urlize}}
</p>

<h3><a href="{% url 'crowd_sourcing:source' %}">Soumettre une source</a></h3>
<h3>Sources ({{ source | length }})</h3>
<ul>
{% for enregistrement in source %}
  <li><a href="{% url 'crowd_sourcing:source' enregistrement.id %}">{{ enregistrement.nom }}</a></li>
{% endfor %}
</ul>